export const tripConstants = {
    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    SEARCH_REQUEST: 'SEARCH_REQUEST',
    SEARCH_SUCCESS: 'SEARCH_SUCCESS',
    SEARCH_FAILURE: 'SEARCH_FAILURE',

    CREATE_TRIPS_REQUEST: 'CREATE_TRIPS_REQUEST',
    CREATE_TRIPS_SUCCESS: 'CREATE_TRIPS_SUCCESS',
    CREATE_TRIPS_FAILURE: 'CREATE_TRIPS_FAILURE',
};
